### ISSUE TITLE
Unable to get shape, dimensions, or image dask data from very large SLDY files

### ISSUE THREAD

**Issue by SergeEParent** [bioio-devs/bioio-sldy#15]
### Describe the Bug

When I open a .sldy file that is very large with bioio I can't get any information about it without my memory being maxed out, including the shape, dimensions, or calling .get_image_dask_data for a single timepoint. I've tried setting `reconstruct_mosaic=False` when calling `BioImage` and that doesn't work either. I've confirmed that I can open and get the shape and dimensions of smaller .sldy files that can be fully loaded to memory.

### Expected Behavior

Expected to get the shape, dimensions, or load a single timepoint relatively quickly like I can with very large OME-TIFFs.

### Reproduction

A minimal working example:

```
from pathlib import Path
from bioio import BioImage
import bioio_sldy
filepath = Path('//allen/aics/assay-dev/MicroscopyData/John Paul/2024/20240305/20240305_T01_001.sldy')
img = BioImage(filepath, reader=bioio_sldy.Reader)
img.dims
```

### Environment

-   OS Version: Windows 10.0.19045
-   bioio Version: 1.1.0
-   bioio-sldy Version: 1.0.1

**Comment by toloudis** [comment]
Are these the values you expected from this file?
(3462, 4, 25, 1712, 1744)
<Dimensions [T: 3462, C: 4, Z: 25, Y: 1712, X: 1744]>

**Comment by toloudis** [comment]
I tihnk I was able to make a big improvement with #16

**Comment by SergeEParent** [comment]
Yes, those are the expected dimensions, thank you!

**Comment by toloudis** [comment]
@SergeEParent when ready, feel free to try  bioio-sldy version 1.0.2

**Comment by SergeEParent** [comment]
Just tried it out and I am happy to report that I can access the image dimensions and get_image_dask_data no problem now (see below for some max-projected slices). Thank you!
![sldy_test_C0](https://github.com/user-attachments/assets/e080e0f3-798a-41c1-9563-6cb85f1203b0)
![sldy_test_C1](https://github.com/user-attachments/assets/b34104b8-0034-428d-beb2-24c0b09f6db5)
